services:
  - type: web
    name: lsc-website
    runtime: node
    buildCommand: |
      cd server && npm install
      cp -r * ..
      cp package.json ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        value: admin 