services:
  - type: web
    name: lsc-website
    runtime: node
    buildCommand: |
      rm -rf node_modules
      npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        value: admin 