services:
  - type: web
    name: lsc-website
    runtime: node
    plan: free
    buildCommand: |
      npm install
      cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        value: saintclaude2024
      - key: DATABASE_URL
        value: ./database.sqlite
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/server
      sizeGB: 1 