services:
  - type: web
    name: lsc-website
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        value: admin
    healthCheckPath: /
    autoDeploy: true 